services:
  server:
    container_name: quizzer_test_server
    environment: 
      - PGUSER=quizuser
      - PGHOST=db
      - PGPASSWORD=quizpw
      - PGDATABASE=quizzer
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
    
  db:
    container_name: quizzer_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=quizzer
      - POSTGRES_PASSWORD=quizpw
volumes:
  test_db:
networks: 
  default:
    name: quizzer_test_test
